# GitHub Pages Configuration

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima

# Exclude files from build
exclude:
  - README.md
  - requirements.txt
  - config.py
  - test_screener.py
  - mutual_fund_screener.py
  - fund_analysis_data.json

# Include files
include:
  - index.html

# Site settings
title: "Indian Mutual Fund Recovery Screener"
description: "Automated screening of beaten-down Indian mutual funds with recovery potential"
author: "AI Financial Analyst"

# URL settings
baseurl: ""
url: ""

# Build settings
plugins:
  - jekyll-sitemap
  - jekyll-feed
