name: Indian Mutual Fund Recovery Screener

on:
  schedule:
    # Runs every weekday at 9:30 AM IST (4:00 AM UTC)
    - cron: '0 4 * * 1-5'  
  workflow_dispatch:  # Allows manual trigger
  push:
    branches: [ main ]

jobs:
  run-screener:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas numpy requests yfinance beautifulsoup4 lxml

    - name: Run Mutual Fund Screener
      run: |
        python mutual_fund_screener.py

    - name: Configure Git
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"

    - name: Commit and push changes
      run: |
        git add index.html fund_analysis_data.json
        git diff --staged --quiet || git commit -m "Update mutual fund analysis - $(date)"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./
        publish_branch: gh-pages
